# GitHub 릴리스 자동 생성 설정
changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-changelog
      - dependencies
    authors:
      - renovate
      - dependabot
  categories:
    - title: 🚀 새로운 기능
      labels:
        - enhancement
        - feature
        - feat
    - title: 🐛 버그 수정
      labels:
        - bug
        - bugfix
        - fix
    - title: 🔒 보안 업데이트
      labels:
        - security
        - vulnerability
    - title: 📚 문서 개선
      labels:
        - documentation
        - docs
    - title: ⚡ 성능 개선
      labels:
        - performance
        - optimization
    - title: 🔧 유지보수
      labels:
        - maintenance
        - chore
        - refactor
    - title: 🧪 테스트
      labels:
        - test
        - testing
    - title: 💥 Breaking Changes
      labels:
        - breaking-change
        - breaking
    - title: 🎨 UI/UX 개선
      labels:
        - ui
        - ux
        - design
    - title: 🏗️ 인프라
      labels:
        - infrastructure
        - docker
        - kubernetes
        - ci/cd