version: '3.8'

services:
  safework-postgres:
    image: registry.jclee.me/safework/postgres:latest
    container_name: safework-postgres
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_DB=safework_db
      - POSTGRES_USER=safework
      - POSTGRES_PASSWORD=safework2024
    # ports:
      # - "4546:5432"  # 외부 노출 금지
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U safework -d safework_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "[{{.Name}}][{{.ImageName}}][safework-postgres-log]"
        labels: "service=safework,component=database"

  safework-redis:
    image: registry.jclee.me/safework/redis:latest
    container_name: safework-redis
    environment:
      - TZ=Asia/Seoul
    # ports:
      # - "4547:6379"  # 외부 노출 금지
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "[{{.Name}}][{{.ImageName}}][safework-redis-log]"
        labels: "service=safework,component=cache"

  safework-app:
    image: registry.jclee.me/safework/app:latest
    container_name: safework-app
    environment:
      - TZ=Asia/Seoul
      - FLASK_ENV=production
      - DB_HOST=safework-postgres
      - DB_NAME=safework_db
      - DB_USER=safework
      - DB_PASSWORD=safework2024
      - REDIS_HOST=safework-redis
      - SECRET_KEY=safework-production-secret-key-2024
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=safework2024
    ports:
      - "4545:4545"
    depends_on:
      safework-postgres:
        condition: service_healthy
      safework-redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4545/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "[{{.Name}}][{{.ImageName}}][safework-app-log]"
        labels: "service=safework,component=application"

volumes:
  postgres_data:
    external: true
    name: safework_postgres_data
  redis_data:
    external: true
    name: safework_redis_data

networks:
  default:
    name: safework-network
    driver: bridge