version: '3.8'

networks:
  safework_network:
    external: true
    name: 638cf4d2dcb5

volumes:
  safework_postgres_data:
    external: true
    name: safework_postgres_data
  safework_redis_data:
    external: true
    name: safework_redis_data
  safework_app_uploads:
    external: true
    name: safework_app_uploads

services:
  safework-postgres:
    image: registry.jclee.me/safework/postgres:latest
    container_name: safework-postgres
    hostname: safework-postgres
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_PASSWORD=${DB_PASSWORD:-safework2024}
      - POSTGRES_DB=${DB_NAME:-safework_db}
      - POSTGRES_USER=${DB_USER:-safework}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - safework_postgres_data:/var/lib/postgresql/data
    networks:
      safework_network:
        ipv4_address: 172.20.0.10
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-safework} -d ${DB_NAME:-safework_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  safework-redis:
    image: registry.jclee.me/safework/redis:latest
    container_name: safework-redis
    hostname: safework-redis
    environment:
      - TZ=Asia/Seoul
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - safework_redis_data:/data
    networks:
      safework_network:
        ipv4_address: 172.20.0.11
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  safework-app:
    image: registry.jclee.me/safework/app:latest
    container_name: safework-app
    hostname: safework-app
    environment:
      - TZ=Asia/Seoul
      - FLASK_CONFIG=${FLASK_CONFIG:-production}
      - DEBUG=${DEBUG:-false}

      # Database Configuration
      - DB_HOST=safework-postgres
      - DB_PORT=5432
      - DB_NAME=${DB_NAME:-safework_db}
      - DB_USER=${DB_USER:-safework}
      - DB_PASSWORD=${DB_PASSWORD:-safework2024}

      # Redis Configuration
      - REDIS_HOST=safework-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=0

      # Application Security
      - SECRET_KEY=${SECRET_KEY:-safework-production-secret-key-2024}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}

      # Flask Settings
      - WTF_CSRF_ENABLED=${WTF_CSRF_ENABLED:-false}
      - UPLOAD_FOLDER=/app/uploads
      - MAX_CONTENT_LENGTH=52428800  # 50MB

      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=/app/logs/app.log
    volumes:
      - safework_app_uploads:/app/uploads
    networks:
      safework_network:
        ipv4_address: 172.20.0.12
    ports:
      - "${APP_PORT:-4545}:4545"
    restart: always
    depends_on:
      safework-postgres:
        condition: service_healthy
      safework-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4545/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
