version: '3.8'

services:
  # MySQL 데이터베이스
  mysql:
    image: registry.jclee.me/safework/mysql:latest
    container_name: safework-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password_2024
      MYSQL_DATABASE: safework_db
      MYSQL_USER: safework
      MYSQL_PASSWORD: safework2024
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - safework-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot_password_2024"]
      timeout: 20s
      retries: 10

  # Redis 캐시
  redis:
    image: registry.jclee.me/safework/redis:latest
    container_name: safework-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6380:6379"
    networks:
      - safework-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 5

  # SafeWork 애플리케이션
  app:
    image: registry.jclee.me/safework/app:latest
    container_name: safework-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      FLASK_APP: app.py
      FLASK_CONFIG: production
      SECRET_KEY: safework-production-secret-key-2024
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: safework
      MYSQL_PASSWORD: safework2024
      MYSQL_DATABASE: safework_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: safework2024
      UPLOAD_FOLDER: /app/uploads
      APP_PORT: 4545
    volumes:
      - app_uploads:/app/uploads
    ports:
      - "4545:4545"
    networks:
      - safework-net
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:4545/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Watchtower 자동 업데이트 (선택사항)
  watchtower:
    image: containrrr/watchtower
    container_name: safework-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --label-enable safework-app safework-mysql safework-redis
    networks:
      - safework-net

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  app_uploads:
    driver: local

networks:
  safework-net:
    driver: bridge
    name: safework-net