version: '3.8'

networks:
  safework_network:

volumes:
  safework_postgres_data:
  safework_redis_data:
  safework_app_uploads:

services:
  safework-postgres:
    image: registry.jclee.me/safework/postgres:latest
    container_name: safework-postgres
    hostname: safework-postgres
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_PASSWORD=safework2024
      - POSTGRES_DB=safework_db
      - POSTGRES_USER=safework
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - safework_postgres_data:/var/lib/postgresql/data
    networks:
      - safework_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U safework -d safework_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "[safework-postgres-log] {{.Name}}"
        labels: "service=safework-postgres,env=production,component=database,stack=safework"

  safework-redis:
    image: registry.jclee.me/safework/redis:latest
    container_name: safework-redis
    hostname: safework-redis
    environment:
      - TZ=Asia/Seoul
      - REDIS_PASSWORD=
    volumes:
      - safework_redis_data:/data
    networks:
      - safework_network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "[safework-redis-log] {{.Name}}"
        labels: "service=safework-redis,env=production,component=database,stack=safework"

  safework-app:
    image: registry.jclee.me/safework/app:latest
    container_name: safework-app
    hostname: safework-app
    environment:
      - TZ=Asia/Seoul
      - FLASK_CONFIG=production
      - DEBUG=false
      - DB_HOST=safework-postgres
      - DB_PORT=5432
      - DB_NAME=safework_db
      - DB_USER=safework
      - DB_PASSWORD=safework2024
      - REDIS_HOST=safework-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - SECRET_KEY=safework-production-secret-key-2024
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=safework2024
      - WTF_CSRF_ENABLED=false
      - UPLOAD_FOLDER=/app/uploads
      - MAX_CONTENT_LENGTH=52428800
      - LOG_LEVEL=INFO
      - LOG_FILE=${APP_LOG_FILE}
    volumes:
      - safework_app_uploads:/app/uploads
    networks:
      - safework_network
    restart: always
    ports:
      - "4545:4545"
    depends_on:
      - safework-postgres
      - safework-redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4545/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "[safework-app-log] {{.Name}}"
        labels: "service=safework-app,env=production,component=application,stack=safework"
