version: '3.8'

# SafeWork Production Stack for Portainer
# 3개 핵심 서비스: app, postgres, redis
# Network: external safework-prod-network (must exist)

networks:
  safework-prod-network:
    external: true

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_uploads:
    driver: local

services:
  safework-postgres:
    image: registry.jclee.me/safework/postgres:latest
    container_name: safework-postgres
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_PASSWORD=safework2024
      - POSTGRES_DB=safework_db
      - POSTGRES_USER=safework
    # ports: # Internal network only
      # - "4546:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safework-prod-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U safework -d safework_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  safework-redis:
    image: registry.jclee.me/safework/redis:latest
    container_name: safework-redis
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=Asia/Seoul
    # ports: # Internal network only
      # - "4547:6379"
    volumes:
      - redis_data:/data
    networks:
      - safework-prod-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  safework-app:
    image: registry.jclee.me/safework/app:latest
    container_name: safework-app
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - TZ=Asia/Seoul
      - FLASK_ENV=production
      - DB_HOST=safework-postgres
      - DB_NAME=safework_db
      - DB_USER=safework
      - DB_PASSWORD=safework2024
      - REDIS_HOST=safework-redis
      - SECRET_KEY=${SECRET_KEY:-safework-production-secret-key-2024}
    ports:
      - "4545:4545"
    volumes:
      - app_uploads:/app/uploads
    networks:
      - safework-prod-network
    depends_on:
      - safework-postgres
      - safework-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4545/health"]
      interval: 30s
      timeout: 10s
      retries: 3