name = "safework"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = "a8d9c67f586acdd15eebcc65ca3aa5bb"

# Production routes
routes = [{ pattern = "safework.jclee.me/*", zone_id = "ed060daac18345f6900fc5a661dc94f9" }]

[[kv_namespaces]]
binding = "SURVEYS"
id = "81ca01654d204124aad62280cebe410e"

[[kv_namespaces]]
binding = "USERS"
id = "6c43ba0c4ecd4a9e80079777ac52b3d9"

[[kv_namespaces]]
binding = "SESSIONS"
id = "2b81b9b02dc34f518d2ca9552804bfef"

[[kv_namespaces]]
binding = "DOCUMENTS"
id = "42e4c9d21d2042cb8ea471a64f5adca6"

[vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
BACKEND_URL = "https://safework.jclee.me"
# SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"