name: 🤖 자동 감지 이슈
description: 시스템에서 자동으로 감지한 코드 품질 이슈
title: "🔍 자동 감지: [이슈 유형] - [간단한 설명]"
labels: ["🤖 claude-ready", "🆕 new"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🔍 자동 감지된 이슈
        
        이 템플릿은 시스템이 자동으로 감지한 코드 품질 이슈를 위한 것입니다.
        Claude가 자동으로 할당되어 해결할 예정입니다.

  - type: dropdown
    id: issue-type
    attributes:
      label: 🏷️ 이슈 유형
      description: 감지된 이슈의 주요 유형을 선택하세요
      options:
        - "TODO/FIXME 주석 정리"
        - "에러 핸들링 개선"
        - "보안 패턴 검토"
        - "성능 최적화"
        - "코드 중복 제거"
        - "테스트 커버리지 개선"
        - "문서화 개선"
        - "기타"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 우선순위
      description: 이슈의 우선순위를 선택하세요
      options:
        - "🔴 P0-urgent (즉시 처리)"
        - "🟠 P1-high (24시간 내)"
        - "🟡 P2-medium (1주일 내)"
        - "🟢 P3-low (여유 있을 때)"
      default: 2
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: 📍 영향 영역
      description: 주요 영향을 받는 영역을 선택하세요
      options:
        - "🎨 Frontend (템플릿, CSS, JS)"
        - "⚙️ Backend (Flask, API, 로직)"
        - "🗄️ Database (모델, 마이그레이션)"
        - "🔒 Security (보안, 인증)"
        - "⚡ Performance (성능, 캐시)"
        - "🐳 DevOps (배포, 인프라)"
        - "🧪 Testing (테스트, 품질)"
      default: 1
    validations:
      required: true

  - type: textarea
    id: detection-details
    attributes:
      label: 🔍 감지 세부사항
      description: 자동 감지된 이슈의 구체적인 내용
      placeholder: |
        예시:
        - app/models.py:42 - TODO: 유효성 검사 추가 필요
        - app/routes/survey.py:156 - FIXME: 에러 핸들링 개선
        - app/static/js/survey.js:89 - 중복 코드 발견
    validations:
      required: true

  - type: textarea
    id: suggested-solution
    attributes:
      label: 💡 제안된 해결책
      description: 이슈 해결을 위한 구체적인 방안 (선택사항)
      placeholder: |
        예시:
        1. TODO 주석을 실제 구현으로 교체
        2. try-catch 블록으로 에러 핸들링 추가
        3. 공통 함수로 중복 코드 리팩토링

  - type: checkboxes
    id: auto-requirements
    attributes:
      label: ✅ 자동 처리 요구사항
      description: Claude가 처리해야 할 작업들
      options:
        - label: "실제 코드 수정 (분석만 하지 말고!)"
          required: true
        - label: "테스트 실행 및 검증"
          required: true
        - label: "커밋 및 PR 생성"
          required: true
        - label: "변경사항 문서화"
          required: false

  - type: markdown
    attributes:
      value: |
        ## 🤖 Claude 자동 처리
        
        이 이슈는 `@claude` 봇이 자동으로 할당받아 처리할 예정입니다.
        
        **처리 예상 시간**: 30분 - 2시간
        **처리 순서**: 분석 → 수정 → 테스트 → PR 생성 → 이슈 종료
        
        ---
        
        💡 **Tip**: 수동으로 Claude를 호출하려면 댓글에 `@claude`를 멘션하세요.