name: ✨ 새 기능 요청
description: 이런 기능이 있으면 좋겠어요
title: "[요청] "
labels: ["enhancement", "new", "claude-ready"]
assignees:
  - qws941

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Claude가 바로 만들어드립니다!
        원하시는 기능을 말씀해주시면 자동으로 구현합니다.

  - type: dropdown
    id: area
    attributes:
      label: 🎯 어디에 필요한가요?
      description: 기능이 필요한 곳을 선택해주세요
      options:
        - 001 근골격계 설문조사
        - 002 신규직원 건강검진
        - 관리자 대시보드
        - 통계/리포트
        - 사용자 관리
        - 데이터 입출력
        - 전체 시스템
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: 💡 어떤 기능인가요?
      description: 원하는 대로 편하게 설명해주세요
      placeholder: |
        예시:
        - "설문 결과를 그래프로 보고 싶어요"
        - "엑셀에서 데이터 한번에 올리고 싶어요"
        - "관리자 페이지에서 직원 검색 기능이 필요해요"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: 🤔 왜 필요한가요?
      description: 이 기능이 있으면 뭐가 좋아지나요?
      placeholder: |
        예시:
        - "매번 하나씩 입력하기 너무 번거로워요"
        - "한눈에 볼 수 있으면 업무가 빨라질 것 같아요"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ 우선순위
      options:
        - 🔴 매우 중요 (없으면 큰일)
        - 🟠 중요 (빨리 필요)
        - 🟡 보통 (있으면 좋음)
        - 🟢 낮음 (언젠가)
      default: 2
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: 📝 참고 화면이나 예시
      description: 비슷한 기능이나 참고할 만한 것이 있나요?
      placeholder: 이미지나 링크를 붙여넣어주세요

  - type: checkboxes
    id: auto-implement
    attributes:
      label: 자동 구현 동의
      options:
        - label: Claude가 자동으로 구현해도 됩니다
          required: false
