name: ✨ Feature Request
description: Suggest new features or enhancements
title: "[FEATURE] "
labels: ["enhancement", "needs-analysis", "claude-ready"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Automated Feature Implementation
        Claude will analyze and implement approved feature requests.

  - type: dropdown
    id: category
    attributes:
      label: 🎯 Feature Category
      description: Which area needs this feature?
      options:
        - "🏥 001 Musculoskeletal Survey"
        - "🩺 002 New Employee Health Check"
        - "📊 Admin Dashboard"
        - "📈 Analytics & Reporting"
        - "👥 User Management"
        - "💾 Data Import/Export"
        - "🔐 Authentication & Security"
        - "⚙️ System Configuration"
        - "🐳 Infrastructure & Deployment"
        - "🌐 API & Integration"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 💡 Feature Description
      description: Describe the feature you'd like to see
      placeholder: |
        Example:
        - "Display survey results as interactive charts"
        - "Bulk import employee data from Excel files"
        - "Add search functionality to admin panel"
        - "Export health check results to PDF reports"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Example:
        - "Manual data entry is time-consuming"
        - "Current reports are hard to understand"
        - "Finding specific records takes too long"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💭 Proposed Solution
      description: How do you envision this feature working?
      placeholder: |
        Describe the workflow, UI elements, or functionality details
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority
      description: How important is this feature?
      options:
        - "🔴 Critical (Blocking current work)"
        - "🟠 High (Needed soon)"
        - "🟡 Medium (Would be helpful)"
        - "🟢 Low (Nice to have)"
      default: 2
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: How will we know when this feature is complete?
      placeholder: |
        - [ ] User can do X
        - [ ] System responds with Y
        - [ ] Data is validated for Z

  - type: textarea
    id: additional_context
    attributes:
      label: 📎 Additional Context
      description: Screenshots, mockups, references, or related issues
      placeholder: Add any files, images, or links that help explain the feature
