# Development Environment Configuration
name: development
description: SafeWork Development Environment Auto Deployment

# Environment Variables
environment:
  FLASK_CONFIG: development
  SECRET_KEY: safework-dev-secret-key-2024
  POSTGRES_HOST: safework2-postgres
  POSTGRES_PORT: 4546
  POSTGRES_DATABASE: safework_db
  POSTGRES_USER: safework
  REDIS_HOST: safework2-redis
  REDIS_PORT: 4547
  
# 배포 전략
deployment:
  strategy: rolling
  max_unavailable: 1
  max_surge: 1
  
# 자동화 설정
automation:
  auto_deploy: true
  branches:
    - develop
  health_check:
    endpoint: /health
    timeout: 30s
    retries: 3
    
# 알림 설정
notifications:
  slack_channel: "#dev-deployments"
  email_recipients:
    - dev-team@company.com