# Production Environment Configuration
name: production
description: SafeWork 프로덕션환경 수동 승인 배포

# 환경 변수
environment:
  FLASK_CONFIG: production
  SECRET_KEY: "{{ secrets.PRODUCTION_SECRET_KEY }}"
  MYSQL_HOST: safework-mysql-prod
  MYSQL_DATABASE: safework_prod_db
  REDIS_HOST: safework-redis-prod
  
# 배포 전략
deployment:
  strategy: blue_green
  approval_required: true
  reviewers:
    - admin
    - lead-developer
  timeout: 24h
  
# 자동화 설정
automation:
  auto_deploy: false
  branches:
    - main
  health_check:
    endpoint: /health
    timeout: 60s
    retries: 5
  pre_deployment:
    - database_backup
    - security_scan
    - performance_test
  post_deployment:
    - smoke_test
    - monitoring_alert_setup
    
# 롤백 설정
rollback:
  enabled: true
  automatic: true
  conditions:
    - health_check_failure
    - high_error_rate
    - performance_degradation
    
# 알림 설정
notifications:
  slack_channel: "#prod-deployments"
  email_recipients:
    - admin@company.com
    - ops-team@company.com
  critical_alerts: true