# SafeWork Environment Variables Configuration
# 🚨 CRITICAL: Copy this to .env and update with secure production values

# === Database Configuration ===
POSTGRES_DB=safework_db
POSTGRES_USER=safework
POSTGRES_PASSWORD=safework2024_CHANGE_THIS_IN_PRODUCTION
DB_HOST=safework-postgres
DB_PORT=5432
DB_NAME=safework_db
DB_USER=safework
DB_PASSWORD=safework2024_CHANGE_THIS_IN_PRODUCTION

# Database Connection Pool Settings
DB_POOL_SIZE=10
DB_POOL_TIMEOUT=30
DB_POOL_RECYCLE=3600
DB_POOL_PRE_PING=true
DB_ECHO=false

# Database Connection Retry Settings
DB_CONNECTION_RETRIES=60
DB_CONNECTION_DELAY=3

# === Redis Configuration ===
REDIS_HOST=safework-redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=
REDIS_TIMEOUT=10
REDIS_SOCKET_CONNECT_TIMEOUT=5
REDIS_SOCKET_KEEPALIVE=true
REDIS_CONNECTION_RETRIES=10
REDIS_CONNECTION_DELAY=1

# Redis Memory and Performance
REDIS_MAXMEMORY=256mb
REDIS_MAXMEMORY_POLICY=allkeys-lru
REDIS_SAVE_INTERVAL=900 1
REDIS_LOG_LEVEL=notice

# === Application Configuration ===
FLASK_CONFIG=production
FLASK_APP=app.py
APP_PORT=4545
SECRET_KEY=GENERATE_SECURE_SECRET_KEY_IN_PRODUCTION
TZ=Asia/Seoul

# CSRF Settings (currently disabled for survey testing)
WTF_CSRF_ENABLED=false
WTF_CSRF_CHECK_DEFAULT=false

# === Admin Configuration ===
ADMIN_USERNAME=admin
ADMIN_PASSWORD=safework2024_CHANGE_THIS_IN_PRODUCTION

# === Security Settings ===
SESSION_COOKIE_SECURE=true
SESSION_COOKIE_HTTPONLY=true
SESSION_COOKIE_SAMESITE=Lax
PERMANENT_SESSION_LIFETIME=3600

# === File Upload Settings ===
UPLOAD_FOLDER=/app/uploads
MAX_CONTENT_LENGTH=52428800

# === URLs ===
DEV_URL=https://safework-dev.jclee.me
PRD_URL=https://safework.jclee.me
LOCAL_URL=http://localhost:4545

# === Container Orchestration ===
# Watchtower settings
WATCHTOWER_POLL_INTERVAL=300
WATCHTOWER_CLEANUP=true

# === Portainer Integration ===
PORTAINER_URL=https://portainer.jclee.me
PORTAINER_API_TOKEN=ptr_lejbr5d8IuYiEQCNpg2VdjFLZqRIEfQiJ7t0adnYQi8=
PORTAINER_ENDPOINT_ID=3

# === GitHub Actions Secrets ===
APP_NAME=safework
REGISTRY_HOST=registry.jclee.me
REGISTRY_USER=admin
REGISTRY_PASSWORD=REGISTRY_PASSWORD_FROM_SECRETS
WATCHTOWER_HTTP_API_TOKEN=WATCHTOWER_TOKEN_FROM_SECRETS
WATCHTOWER_URL=https://watchtower.jclee.me

# === Monitoring and Logging ===
LOG_LEVEL=INFO
LOG_FORMAT=%(asctime)s - %(name)s - %(levelname)s - %(message)s
LOG_FILE=/app/logs/safework.log
LOG_MAX_BYTES=10485760
LOG_BACKUP_COUNT=5

# === Performance Monitoring ===
MONITOR_ENABLED=true
METRICS_PORT=9090
HEALTH_CHECK_INTERVAL=30
HEALTH_CHECK_TIMEOUT=10
HEALTH_CHECK_RETRIES=3

# === SafeWork Specific Settings ===
SURVEY_ANONYMOUS_USER_ID=1
SURVEY_SESSION_TIMEOUT=3600
SURVEY_MAX_SUBMISSIONS_PER_IP=100
SURVEY_RATE_LIMIT=100/hour

# Form Processing Settings
FORM_MAX_FILE_SIZE=50MB
FORM_ALLOWED_EXTENSIONS=.pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png
FORM_UPLOAD_TIMEOUT=300

# MSDS Integration Settings
MSDS_API_ENABLED=true
MSDS_API_TIMEOUT=30
MSDS_CACHE_TTL=86400

# Safety Education Settings
EDUCATION_VIDEO_MAX_SIZE=500MB
EDUCATION_COMPLETION_THRESHOLD=80
EDUCATION_CERTIFICATE_ENABLED=true