version: '3.8'

# SafeWork 로컬 개발환경 Docker Compose
# 새로운 모듈화된 구조를 위한 설정

services:
  safework-postgres:
    build:
      context: ./infrastructure/docker/postgres
      dockerfile: Dockerfile
    container_name: safework-postgres
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_PASSWORD=${DB_PASSWORD:-safework2024}
      - POSTGRES_DB=safework_db
      - POSTGRES_USER=safework
    ports:
      - "4546:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - safework_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U safework -d safework_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  safework-redis:
    build:
      context: ./infrastructure/docker/redis
      dockerfile: Dockerfile
    container_name: safework-redis
    environment:
      - TZ=Asia/Seoul
    ports:
      - "4547:6379"
    volumes:
      - redis_data:/data
    networks:
      - safework_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  safework-app:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    container_name: safework-app
    environment:
      - TZ=Asia/Seoul
      - FLASK_ENV=development
      - DB_HOST=safework-postgres
      - DB_NAME=safework_db
      - DB_USER=safework
      - DB_PASSWORD=${DB_PASSWORD:-safework2024}
      - REDIS_HOST=safework-redis
      - SECRET_KEY=${SECRET_KEY:-dev-only-key-CHANGE-IN-PRODUCTION}
    ports:
      - "4545:4545"
    volumes:
      - ./src/app:/app
      - app_uploads:/app/uploads
    networks:
      - safework_network
    depends_on:
      - safework-postgres
      - safework-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4545/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_uploads:
    driver: local

networks:
  safework_network:
    driver: bridge
    name: safework_network