name = "safework"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces
[[kv_namespaces]]
binding = "SAFEWORK_KV"
preview_id = "54cbaf6aeff64ebbab07adb7ac56f5c8"
id = "54cbaf6aeff64ebbab07adb7ac56f5c8"

# Environment variables
[vars]
JWT_SECRET = "safework-jwt-secret-2024-production"
ADMIN_USERNAME = "admin"
BACKEND_URL = "https://safework.jclee.me"
ENVIRONMENT = "production"

# Routes
[[routes]]
pattern = "safework.jclee.me/survey/001_musculoskeletal_symptom_survey"
zone_name = "jclee.me"

[[routes]]
pattern = "safework.jclee.me/survey/002_musculoskeletal_symptom_program"
zone_name = "jclee.me"

[[routes]]
pattern = "safework.jclee.me/api/*"
zone_name = "jclee.me"

# Rate limiting removed for Free plan

# Build configuration removed to prevent infinite loop

# Development environment
[env.development]
name = "safework-dev"
vars = { BACKEND_URL = "http://localhost:4545", DEBUG = "true", ENVIRONMENT = "development" }

# Production environment
[env.production]
name = "safework-prod"

[env.production.vars]
JWT_SECRET = "safework-jwt-secret-2024-production"
ADMIN_USERNAME = "admin"
BACKEND_URL = "https://safework.jclee.me"
DEBUG = "false"
ENVIRONMENT = "production"

# D1 Database - Will be configured by GitHub Actions
# [[d1_databases]]
# binding = "SAFEWORK_DB"
# database_name = "safework-db"
# database_id = "will-be-configured-by-github-actions"