name = "safework"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces - CF Native Naming Convention
# Primary storage: SESSION_DATA, API_CONFIG, FORM_STRUCTURES
[[kv_namespaces]]
binding = "SESSION_STORE"
preview_id = "placeholder-session-store-preview"
id = "placeholder-session-store-production"

# Cache layer: COMPUTED_DATA, STATISTICS, TEMP_RESPONSES
[[kv_namespaces]]
binding = "CACHE_LAYER"
preview_id = "placeholder-cache-layer-preview"
id = "placeholder-cache-layer-production"

# Authentication: JWT_TOKENS, API_KEYS, USER_SESSIONS
[[kv_namespaces]]
binding = "AUTH_STORE"
preview_id = "placeholder-auth-store-preview"
id = "placeholder-auth-store-production"

# Environment variables
[vars]
JWT_SECRET = "safework-jwt-secret-2024-production"
ADMIN_USERNAME = "admin"
BACKEND_URL = "https://safework.jclee.me"
ENVIRONMENT = "production"

# Routes
[[routes]]
pattern = "safework.jclee.me/survey/001_musculoskeletal_symptom_survey"
zone_name = "jclee.me"

[[routes]]
pattern = "safework.jclee.me/survey/002_musculoskeletal_symptom_program"
zone_name = "jclee.me"

[[routes]]
pattern = "safework.jclee.me/api/*"
zone_name = "jclee.me"

# Rate limiting removed for Free plan

# Build configuration removed to prevent infinite loop

# Development environment
[env.development]
name = "safework-dev"
vars = { BACKEND_URL = "http://localhost:4545", DEBUG = "true", ENVIRONMENT = "development" }

# Production environment
[env.production]
name = "safework"

[env.production.vars]
JWT_SECRET = "safework-jwt-secret-2024-production"
ADMIN_USERNAME = "admin"
BACKEND_URL = "https://safework.jclee.me"
DEBUG = "false"
ENVIRONMENT = "production"

# D1 Database - CF Native Naming Convention
# Primary database: USER_DATA, SURVEY_RESPONSES, AUDIT_LOGS
[[d1_databases]]
binding = "PRIMARY_DB"
database_name = "safework-primary"
database_id = "placeholder-primary-db-production"

# Analytics database: STATISTICS, REPORTS, AGGREGATED_DATA
[[d1_databases]]
binding = "ANALYTICS_DB"
database_name = "safework-analytics"
database_id = "placeholder-analytics-db-production"