name = "safework2"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces - Will be created dynamically by GitHub Actions

# Environment variables
[vars]
JWT_SECRET = "safework-jwt-secret-2024-production"
ADMIN_USERNAME = "admin"
BACKEND_URL = "https://safework2.jclee.me"
ENVIRONMENT = "production"

# Routes
[[routes]]
pattern = "safework2.jclee.me/*"
zone_name = "jclee.me"

# Rate limiting removed for Free plan

# Build configuration removed to prevent infinite loop

# Development environment
[env.development]
name = "safework2-dev"
vars = { BACKEND_URL = "http://localhost:4545", DEBUG = "true", ENVIRONMENT = "development" }

# Production environment
[env.production]
name = "safework2-prod"

[env.production.vars]
JWT_SECRET = "safework-jwt-secret-2024-production"
ADMIN_USERNAME = "admin"
BACKEND_URL = "https://safework2.jclee.me"
DEBUG = "false"
ENVIRONMENT = "production"

# KV Namespaces for production - Will be created dynamically by GitHub Actions