# ============================================
# SafeWork - Cloudflare Workers Configuration
# ============================================

name = "safework"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]
account_id = "a8d9c67f586acdd15eebcc65ca3aa5bb"
workers_dev = true

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# ============================================
# Production Routes
# ============================================
[[routes]]
pattern = "safework.jclee.me/*"
zone_name = "jclee.me"

# ============================================
# Environment Variables (Production)
# ============================================
[vars]
# SECURITY WARNING: DO NOT store secrets here!
# JWT_SECRET, ADMIN_PASSWORD_HASH, and SLACK_WEBHOOK_URL must be stored in Cloudflare Secrets
# Use: wrangler secret put JWT_SECRET
#      wrangler secret put ADMIN_PASSWORD_HASH
#      wrangler secret put SLACK_WEBHOOK_URL
#      wrangler secret put SLACK_BOT_TOKEN (optional, for advanced features)
# See: SECURITY_MIGRATION_GUIDE.md for instructions

ADMIN_USERNAME = "admin"
BACKEND_URL = "https://safework.jclee.me"
DEBUG = "false"
ENVIRONMENT = "production"

# Slack Integration (URLs stored as secrets)
# Get webhook URL from: https://n8n.jclee.me or Slack App settings
# SLACK_WEBHOOK_URL = (stored as secret)
# SLACK_BOT_TOKEN = (stored as secret, optional)

# ============================================
# KV Namespaces (Production)
# ============================================
[[kv_namespaces]]
binding = "SAFEWORK_KV"
id = "54cbaf6aeff64ebbab07adb7ac56f5c8"  # production-SAFEWORK_KV

[[kv_namespaces]]
binding = "CACHE_LAYER"
id = "5a30c645c88644068089f1733b2c81b9"

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "e6a6466f4c53466087f6fdd2cd6ca001"

# ============================================
# D1 Database (Production)
# ============================================
[[d1_databases]]
binding = "PRIMARY_DB"
database_name = "safework-primary"
database_id = "d1db1d92-f598-415e-910f-1af511bc182f"

# ============================================
# R2 Object Storage (Production)
# ============================================
[[r2_buckets]]
binding = "SAFEWORK_STORAGE"
bucket_name = "safework-storage-prod"

# ============================================
# AI Gateway (Production)
# ============================================
[ai]
binding = "AI"
