# ⚠️ 이 워크플로우는 master-issue-orchestrator.yml로 통합되었습니다.
# 배포 기능은 safe-deployment.yml에서 처리합니다.

name: "🚀 Automated Deployment (DEPRECATED)"

on:
  # 기본적으로 비활성화 - 마스터 오케스트레이터가 배포를 처리
  workflow_dispatch:
    inputs:
      redirect_to_new:
        description: '새 워크플로우로 리디렉션'
        required: false
        default: true
        type: boolean

jobs:
  migration-notice:
    runs-on: ubuntu-latest
    steps:
      - name: 📢 배포 워크플로우 통합 안내
        run: |
          echo "⚠️ 자동 배포 시스템이 통합되었습니다"
          echo ""
          echo "🚀 새로운 배포 시스템:"
          echo "  - master-issue-orchestrator.yml: 통합 이슈 처리 및 배포 트리거"
          echo "  - safe-deployment.yml: Blue-Green 무중단 배포"
          echo "  - Docker 레지스트리 자동 푸시"
          echo "  - 환경별 조건부 배포 전략"
          echo ""
          echo "🔄 사용법:"
          echo "  1. 이슈 생성/편집 → 자동 우선순위 분석"
          echo "  2. P0/P1 이슈 → 자동 긴급 배포"
          echo "  3. 일반 이슈 → 안전한 점진적 배포"
          echo "  4. registry.jclee.me 자동 푸시"
          
      - name: 🔄 배포 리디렉션 안내
        if: inputs.redirect_to_new == 'true'
        run: |
          echo "📍 새로운 배포 시스템으로 리디렉션됩니다."
          echo ""
          echo "🎯 권장 사용 패턴:"
          echo "  - 긴급 배포: P0 라벨로 이슈 생성"
          echo "  - 일반 배포: enhancement/bug 라벨로 이슈 생성" 
          echo "  - 수동 배포: safe-deployment.yml workflow_dispatch 사용"
          echo ""
          echo "📊 통합 후 개선사항:"
          echo "  - 이슈 우선순위 기반 자동 배포"
          echo "  - Sub-agents 연동으로 스마트 배포 결정"
          echo "  - UI 스크린샷 검증 시스템"
          echo "  - 실패 시 자동 롤백"
          echo "  - 사용자 태깅 및 알림"