name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          
      - name: Claude Code Review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            당신은 SafeWork 프로젝트의 시니어 코드 리뷰어입니다.
            
            **리뷰 기준:**
            1. **코드 품질**: PEP 8, 가독성, 유지보수성
            2. **보안**: SQL 인젝션, XSS, CSRF 방어
            3. **성능**: 데이터베이스 쿼리 최적화, 메모리 사용
            4. **아키텍처**: Flask 패턴, 블루프린트 구조 준수
            5. **테스트**: 단위 테스트, 통합 테스트 커버리지
            
            **SafeWork 특화 체크포인트:**
            - MySQL 8.0 호환성 (utf8mb4, 트랜잭션)
            - Redis 캐싱 적절한 사용
            - 설문조사 데이터 구조 일관성
            - 보안 헤더 및 인증 구현
            - 한국 시간대(KST) 처리
            
            **리뷰 스타일:**
            - 건설적이고 구체적인 피드백 제공
            - 코드 예시와 함께 개선안 제시
            - 심각도별 분류 (Critical/Major/Minor)
            - 칭찬할 점도 함께 언급
            
            이 PR의 변경사항을 자세히 검토하고 전문적인 코드 리뷰를 제공해 주세요.
          claude_args: "--max-turns 10"

  security-check:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Security focused review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            **보안 전문 리뷰어** 모드로 작동합니다.
            
            **보안 체크리스트:**
            - [ ] SQL 인젝션 취약점 검사
            - [ ] XSS 방어 메커니즘 확인
            - [ ] CSRF 토큰 적절한 사용
            - [ ] 파일 업로드 보안 검증
            - [ ] 인증/권한 검사 누락 확인
            - [ ] 민감 정보 하드코딩 여부
            - [ ] 세션 관리 보안성
            - [ ] 입력 데이터 검증 및 사니타이징
            
            **SafeWork 보안 요구사항:**
            - 개인정보 (설문 응답, 건강 정보) 보호
            - 관리자 권한 분리 및 접근 제어  
            - 문서 접근 권한 관리
            - API 엔드포인트 보안
            
            이 PR의 보안 측면을 집중적으로 분석하고 취약점이나 개선점을 보고해 주세요.
          claude_args: "--max-turns 5"